### ISSUE TITLE
Error during installation via pip

### ISSUE THREAD

**Issue by Bastiiiiii** [BerkeleyAutomation/python-fcl#14]
Hello,

I am quite new to python. I use Python 3.6, Windows 10 and want to install fcl via pip 'pip install python-fcl'. Do I need octomap before installing fcl? I can not install octomap aswell.

Terminal respond:
Collecting python-fcl
  Using cached https://files.pythonhosted.org/packages/b4/c9/522b42c9e6842125686deac3a87b64739dac8ad8f313d02288cbe255efe2/python-fcl-0.0.11.tar.gz
    ERROR: Complete output from command python setup.py egg_info:
    ERROR: Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\roehr\AppData\Local\Temp\pip-install-z66h54fz\python-fcl\setup.py", line 45, in <module>
        raise NotImplementedError(sys.platform)
    NotImplementedError: win32
    ----------------------------------------
ERROR: Command "python setup.py egg_info" failed with error code 1 in C:\Users\roehr\AppData\Local\Temp\pip-install-z66h54fz\python-fcl\

Can you help me out? 

Thank you!

**Comment by sbjikimm** [comment]
Did you solve that? i'm facing same problem. It would be nice, if you let me know how to fix that.

**Comment by vagarkav** [comment]
@Bastiiiiii, why did you close the issue? Have you solved it? I'm running into the same.
