### ISSUE TITLE
Cannot install under OSX Mojave (10.14) using pip and python 3.7

### ISSUE THREAD

**Issue by misan** [BerkeleyAutomation/python-fcl#15]
I have installed octomap before but once I type
`$ pip3 install python-fcl`

It fails with this output:

Collecting python-fcl
  Using cached https://files.pythonhosted.org/packages/d6/1a/51e9a3cf8473f297226396ad508702483f4fe3df9bb60676b35d2aca340d/python-fcl-0.0.12.tar.gz
Requirement already satisfied: numpy in /Users/misan/Library/Python/3.7/lib/python/site-packages (from python-fcl) (1.16.4)
Requirement already satisfied: cython in /Users/misan/Library/Python/3.7/lib/python/site-packages (from python-fcl) (0.29.10)
Building wheels for collected packages: python-fcl
  Building wheel for python-fcl (setup.py) ... error
  ERROR: Complete output from command /usr/local/opt/python/bin/python3.7 -u -c 'import setuptools, tokenize;__file__='"'"'/private/var/folders/rz/kw6z5q015bx5_zhls77kznz00000gn/T/pip-install-zz_36jyd/python-fcl/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /private/var/folders/rz/kw6z5q015bx5_zhls77kznz00000gn/T/pip-wheel-w3h9lffv --python-tag cp37:
  ERROR: running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.macosx-10.14-x86_64-3.7
  creating build/lib.macosx-10.14-x86_64-3.7/fcl
  copying fcl/collision_data.py -> build/lib.macosx-10.14-x86_64-3.7/fcl
  copying fcl/version.py -> build/lib.macosx-10.14-x86_64-3.7/fcl
  copying fcl/__init__.py -> build/lib.macosx-10.14-x86_64-3.7/fcl
  running build_ext
  cythoning fcl/fcl.pyx to fcl/fcl.cpp
  building 'fcl.fcl' extension
  creating build/temp.macosx-10.14-x86_64-3.7
  creating build/temp.macosx-10.14-x86_64-3.7/fcl
  clang -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/usr/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/System/Library/Frameworks/Tk.framework/Versions/8.5/Headers -I/usr/include -I/usr/local/include -I/usr/include/eigen3 -I/Users/misan/Library/Python/3.7/lib/python/site-packages/numpy/core/include -I/usr/local/include -I/usr/local/opt/openssl/include -I/usr/local/opt/sqlite/include -I/usr/local/Cellar/python/3.7.2_2/Frameworks/Python.framework/Versions/3.7/include/python3.7m -c fcl/fcl.cpp -o build/temp.macosx-10.14-x86_64-3.7/fcl/fcl.o -std=c++11
  In file included from fcl/fcl.cpp:619:
  In file included from /Users/misan/Library/Python/3.7/lib/python/site-packages/numpy/core/include/numpy/arrayobject.h:4:
  In file included from /Users/misan/Library/Python/3.7/lib/python/site-packages/numpy/core/include/numpy/ndarrayobject.h:12:
  In file included from /Users/misan/Library/Python/3.7/lib/python/site-packages/numpy/core/include/numpy/ndarraytypes.h:1822:
  /Users/misan/Library/Python/3.7/lib/python/site-packages/numpy/core/include/numpy/npy_1_7_deprecated_api.h:17:2: warning: "Using deprecated NumPy API, disable it with "          "#define NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION" [-W#warnings]
  #warning "Using deprecated NumPy API, disable it with " \
   ^
  fcl/fcl.cpp:627:10: fatal error: 'fcl/data_types.h' file not found
  #include "fcl/data_types.h"
           ^~~~~~~~~~~~~~~~~~
  1 warning and 1 error generated.
  error: command 'clang' failed with exit status 1

  ERROR: Failed building wheel for python-fcl
  Running setup.py clean for python-fcl
Failed to build python-fcl
Installing collected packages: python-fcl
  Running setup.py install for python-fcl ... error
    ERROR: Complete output from command /usr/local/opt/python/bin/python3.7 -u -c 'import setuptools, tokenize;__file__='"'"'/private/var/folders/rz/kw6z5q015bx5_zhls77kznz00000gn/T/pip-install-zz_36jyd/python-fcl/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/var/folders/rz/kw6z5q015bx5_zhls77kznz00000gn/T/pip-record-oh_p8l97/install-record.txt --single-version-externally-managed --compile:
    ERROR: running install
    running build
    running build_py
    creating build
    creating build/lib.macosx-10.14-x86_64-3.7
    creating build/lib.macosx-10.14-x86_64-3.7/fcl
    copying fcl/collision_data.py -> build/lib.macosx-10.14-x86_64-3.7/fcl
    copying fcl/version.py -> build/lib.macosx-10.14-x86_64-3.7/fcl
    copying fcl/__init__.py -> build/lib.macosx-10.14-x86_64-3.7/fcl
    running build_ext
    skipping 'fcl/fcl.cpp' Cython extension (up-to-date)
    building 'fcl.fcl' extension
    creating build/temp.macosx-10.14-x86_64-3.7
    creating build/temp.macosx-10.14-x86_64-3.7/fcl
    clang -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/usr/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/System/Library/Frameworks/Tk.framework/Versions/8.5/Headers -I/usr/include -I/usr/local/include -I/usr/include/eigen3 -I/Users/misan/Library/Python/3.7/lib/python/site-packages/numpy/core/include -I/usr/local/include -I/usr/local/opt/openssl/include -I/usr/local/opt/sqlite/include -I/usr/local/Cellar/python/3.7.2_2/Frameworks/Python.framework/Versions/3.7/include/python3.7m -c fcl/fcl.cpp -o build/temp.macosx-10.14-x86_64-3.7/fcl/fcl.o -std=c++11
    In file included from fcl/fcl.cpp:619:
    In file included from /Users/misan/Library/Python/3.7/lib/python/site-packages/numpy/core/include/numpy/arrayobject.h:4:
    In file included from /Users/misan/Library/Python/3.7/lib/python/site-packages/numpy/core/include/numpy/ndarrayobject.h:12:
    In file included from /Users/misan/Library/Python/3.7/lib/python/site-packages/numpy/core/include/numpy/ndarraytypes.h:1822:
    /Users/misan/Library/Python/3.7/lib/python/site-packages/numpy/core/include/numpy/npy_1_7_deprecated_api.h:17:2: warning: "Using deprecated NumPy API, disable it with "          "#define NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION" [-W#warnings]
    #warning "Using deprecated NumPy API, disable it with " \
     ^
    fcl/fcl.cpp:627:10: fatal error: 'fcl/data_types.h' file not found
    #include "fcl/data_types.h"
             ^~~~~~~~~~~~~~~~~~
    1 warning and 1 error generated.
    error: command 'clang' failed with exit status 1
    ----------------------------------------
ERROR: Command "/usr/local/opt/python/bin/python3.7 -u -c 'import setuptools, tokenize;__file__='"'"'/private/var/folders/rz/kw6z5q015bx5_zhls77kznz00000gn/T/pip-install-zz_36jyd/python-fcl/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/var/folders/rz/kw6z5q015bx5_zhls77kznz00000gn/T/pip-record-oh_p8l97/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /private/var/folders/rz/kw6z5q015bx5_zhls77kznz00000gn/T/pip-install-zz_36jyd/python-fcl/

**Comment by misan** [comment]
Ok, I need to install fcl first, and before that libccd ... pip does not do that apparently :-(

**Comment by misan** [comment]
Ok, I closed it too early. I am still stuck at the same point now that I have installed eigen, libccd and fcl. 

And I am in fact not able to see any data_types.h in fcl include files.

**Comment by misan** [comment]
I guess there is a versioning problem.

`$ brew install fcl `

did the trick for me.

**Comment by menglaili** [comment]
I have installed eigen, fcl using Homebrew and libccd using Makefile, but I still face the same problem. What versions do you choose for these dependencies?

**Comment by Amar1729** [comment]
This isn't in the bullets under [FCL's releases](https://github.com/flexible-collision-library/fcl/releases), but it looks like in version 0.6.0 [`data_types.h`](https://github.com/flexible-collision-library/fcl/blob/0.5.0/include/fcl/data_types.h) was renamed to [`common/types.h`](https://github.com/flexible-collision-library/fcl/blob/v0.6.0/include/fcl/common/types.h).

@menglaili I think when this issue was originally opened, homebrew-core had FCL version 0.5.0 (whereas current is 0.6.0).

Installing `python-fcl` works for me if I checkout back to fcl@0.5.0 with homebrew and build that, but I guess this library should probably be updated to reflect the new file location.

**Comment by Amar1729** [comment]
This isn't in the bullets under [FCL's releases](https://github.com/flexible-collision-library/fcl/releases), but it looks like in version 0.6.0 [`data_types.h`](https://github.com/flexible-collision-library/fcl/blob/0.5.0/include/fcl/data_types.h) was renamed to [`common/types.h`](https://github.com/flexible-collision-library/fcl/blob/v0.6.0/include/fcl/common/types.h).

@menglaili I think when this issue was originally opened, homebrew-core had FCL version 0.5.0 (whereas current is 0.6.1).

Installing `python-fcl` works for me if I checkout back to fcl@0.5.0 with homebrew and build that, but I guess this library should probably be updated to reflect the new file location.

Looks like there are two open PRs for updating to 0.6.0: https://github.com/BerkeleyAutomation/python-fcl/pulls

**Comment by Aniwax** [comment]
Why is this issue closed? Since python-fcl doesn't work with fcl@0.6.0  yet?
Btw, `brew install fcl@0.5.0` is not working for me. Can someone give me a hint on how to install the 0.5.0 version from the zip file?

**Comment by Amar1729** [comment]
@Aniwax I literally checked out the homebrew repo back in time --

1. cd to homebrew's repo (typically `/usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula`)

2. determine the last commit for `fcl.rb` 5.x (`git log -- fcl.rb` and read the log messages) and checkout to that commit
  - in this case i used `git checkout 75dc086c11`

3. install fcl normally `brew install fcl`
  a. pin the formula so it doesn't auto upgrade (`brew pin fcl`)

4. checkout back to master (`git checkout master`)

This is a bit of a hack since homebrew no longer keeps old versions except for very highly-used formuale.

**Comment by Amar1729** [comment]
This issue is probably still relevant until pull #20 or #21 are finished.

**Comment by Aniwax** [comment]
Thanks a lot! @Amar1729
