### ISSUE TITLE
fcl/fcl_defs.pxd is missing in sdist generated tarballs

### ISSUE THREAD

**Issue by ocordes** [BerkeleyAutomation/python-fcl#2]
Hi,
the uploaded pypi tarball for python-fcl doesn't contain the file
fcl/fcl_defs.pxd and therefore on all non linux machines pip install python-fcl is failing. 
I triggered the issue down to a missing line in MANIFEST.in:

include fcl/fcl_defs.pxd

will fix this problem! 

Please add this asap and redistribute the pypi tar balls.

Cheers,
  Oliver

**Comment by mmatl** [comment]
Sounds good, will do! Thanks for the heads up.

**Comment by mmatl** [comment]
This has been fixed in 8c9cf688072ce259928c750383a00287f5d85575. Thanks for the heads-up on it, and sorry for the delayed fix!
