### ISSUE TITLE
Can't install Python-FCL, please help

### ISSUE THREAD

**Issue by Georgy1987** [BerkeleyAutomation/python-fcl#26]
PS C:\Users\...\Desktop\Python\venv> pip install python-fcl
Collecting python-fcl
  Using cached python-fcl-0.0.12.tar.gz (17 kB)
    ERROR: Command errored out with exit status 1:
     command: 'c:\users\...\appdata\local\programs\python\python39\python.exe' -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\...\\AppData\\Local\\Temp\\pip-install-cds4ao_r\\python-fcl_94f219e272744b3d9053c1de3b1b1da8\\setup.py'"'"'; __file__='"'"'C:\\Users\\...\\AppData\\Local\\Temp\\pip-install-cds4ao_r\\python-fcl_94f219e272744b3d9053c1de3b1b1da8\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\...\AppData\Local\Temp\pip-pip-egg-info-yld_5lnw'
         cwd: C:\Users\...\AppData\Local\Temp\pip-install-cds4ao_r\python-fcl_94f219e272744b3d9053c1de3b1b1da8\
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\...\AppData\Local\Temp\pip-install-cds4ao_r\python-fcl_94f219e272744b3d9053c1de3b1b1da8\setup.py", line 45, in <module>
        raise NotImplementedError(sys.platform)
    NotImplementedError: win32
    ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/d6/1a/51e9a3cf8473f297226396ad508702483f4fe3df9bb60676b35d2aca340d/python-fcl-0.0.12.tar.gz#sha256=f5e60c4f2f43f72f0029435dd4bac61a7e5867c53cf14adc54afe67dc8ad3510 (from https://pypi.org/simple/python-fcl/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

**Comment by Pebaz** [comment]
Please refer to [python-fcl-win32](https://github.com/Pebaz/python-fcl) for Windows support.

**Comment by mjd3** [comment]
There are now wheels available on pypi as well for windows so I am closing this issue. Please feel free to reopen if you continue to experience any issues.
