### ISSUE TITLE
Update PyPi Repo

### ISSUE THREAD

**Issue by Eric-Vin** [BerkeleyAutomation/python-fcl#40]
Would it be possible to update the PyPi repo with the new wheels? It looks like it hasn't been updated since 2019.

**Comment by schnellerblitz99** [comment]
Have the same issue right now when I try to import fcl:
`import fcl`
> lib/python3.8/site-packages/fcl/fcl.cpython-38-x86_64-linux-gnu.so: undefined symbol: _ZNK3fcl10BVSplitterINS_6OBBRSSEE5applyERKNS_6Vec3fXINS_7details8Vec3DataIdEEEE

I guess this is related.

**Comment by mmatl** [comment]
@mikedh It looks like there's a slight problem with the deploy pipeline. The wheels for 0.6.1 are built nicely and work well (20.04, Python 3.9) but they haven't been deployed to PyPi. What needs to happen to make that work?

**Comment by mjd3** [comment]
@mmatl @mikedh Ah I think this was due to the new API token functionality for pypi; the user in the pipeline should be `__token__`. This has been fixed in the latest commit and the 0.6.1 wheels are on pypi now!

**Comment by mikedh** [comment]
Awesome thanks @mjd3! And apologies for forgetting about this oops 😄

**Comment by mmatl** [comment]
@mjd3 Thank you so much :)

**Comment by Eric-Vin** [comment]
Thanks so much! This will be super helpful.
