### ISSUE TITLE
Macos with m1 chip support

### ISSUE THREAD

**Issue by fengyc** [BerkeleyAutomation/python-fcl#46]
On macos with m1 chip, pip could not find the latest version 0.6.1.

```
$ pip install python-fcl==0.6.1                                                 
ERROR: Could not find a version that satisfies the requirement python-fcl==0.6.1 (from versions: 0.0.4, 0.0.6, 0.0.7, 0.0.9, 0.0.10, 0.0.11, 0.0.12)
ERROR: No matching distribution found for python-fcl==0.6.1
```

**Comment by fengyc** [comment]
Steps to install in macos (ARM cpu)
```
brew install fcl eigen octomap
CPATH=$(brew --prefix)/include:$(brew --prefix)/include/eigen3 \
LD_LIBRARY_PATH=$(brew --prefix)/lib \
pip install python-fcl
```

**Comment by mikedh** [comment]
Hey, Github released mac M1 CI runners finally and it appears to have built and tested successfully in #74 with `macosx_arm64` wheels on both Github and [PyPi](https://pypi.org/project/python-fcl/0.7.0.6/#files)

You should be able to `pip install --upgrade python-fcl` and get them. I'm going to close this but feel free to open new issues if the wheels don't work.
