### ISSUE TITLE
Mac ARM version

### ISSUE THREAD

**Issue by lkaelbling** [BerkeleyAutomation/python-fcl#49]
Has anyone built MacOS ARM versions for Python 3.9 or 3.10?    When I try to compile from source I get a lot of C++ errors that I am not equipped to try to fix.

I'd really appreciate any help!

**Comment by fengyc** [comment]
See #47 . You need to install fcl using brew and then 
```
CPATH=$(brew --prefix)/include:$(brew --prefix)/include/eigen3 \
LD_LIBRARY_PATH=$(brew --prefix)/lib \
pip install python-fcl
```

I figured out the solution from source code of setup.py.

**Comment by mjd3** [comment]
Closing this as a duplicate of #46; can continue conversation there.
