### ISSUE TITLE
Add tag 0.0.9 to push to pypi.org

### ISSUE THREAD

**Issue by iceflame89** [BerkeleyAutomation/python-fcl#6]
@mmatl  Could you please add a tag 0.0.9  for  latest version 0.0.9 with octree support. So that travis could push the latest package to pypi.org.  
Thanks.

**Comment by mikedh** [comment]
Tagged, also the build finished and the wheels made it to pypi: https://pypi.org/project/python-fcl/#files

**Comment by iceflame89** [comment]
Great!
