### ISSUE TITLE
Incorrect project links on PyPI?

### ISSUE THREAD

**Issue by musicinmybrain** [BerkeleyAutomation/python-fcl#71]
The PyPI project links to the fork https://github.com/CyrilWaechter/python-fcl as the project homepage; links in the “GitHub Statistics” section also go to that project.

Based on the version numbers in https://pypi.org/project/python-fcl/#files, it looks like releases to PyPI are not built from that fork, which has not been updated in some time, but from this repository (https://github.com/BerkeleyAutomation/python-fcl/).

Could the PyPI metadata be updated to link to the correct project?

**Comment by mikedh** [comment]
Fixed by #74 which migrated to a `pyproject.toml`.
