### ISSUE TITLE
Identifying the CollisionObjects that overlap using collide()

### ISSUE THREAD

**Issue by lt5bf** [BerkeleyAutomation/python-fcl#8]
As per my email, I have a question about identifying the objects that collide using python-fcl:

In my use case, I have many cylinder `CollisionObjects `in one `manager`. When I call `manager.collide()`, I get back the number of contact points and their locations and the distance between the objects that collide.

However, I'd like to know which objects are actually colliding. For example, if I have 4 `CollisionObjects `named `obj1, ..., obj4` in my manager and only 2 of them collide, it appears that the `collide()` method only returns objects named `o1 `and `o2`. Do `o1 `and `o2 `contain identifiers that map them back to one of the original `obj ``CollisionObjects`?

Thanks in advance,
Lee

**Comment by mmatl** [comment]
Good question! You can do this indirectly with a bit of wrapper code. The `o1` and `o2` within each `Contact` object are actually the raw `CollisionGeometry` objects that you created for each `CollisionObject`. Weird, I know, but it's part of the FCL API unfortunately. So, all you have to do is make a map from collision *geometry* ids to either the actual collision *objects* they correspond to or to a string identifier for each object if that's what you want.

Here's an example.

```python
import fcl
import numpy as np

# Create collision geometry and objects
geom1 = fcl.Cylinder(1.0, 1.0)
obj1 = fcl.CollisionObject(geom1)

geom2 = fcl.Cylinder(1.0, 1.0)
obj2 = fcl.CollisionObject(geom2, fcl.Transform(np.array([0.0, 0.0, 0.3])))

geom3 = fcl.Cylinder(1.0, 1.0)
obj3 = fcl.CollisionObject(geom3, fcl.Transform(np.array([0.0, 0.0, 3.0])))

geoms = [geom1, geom2, geom3]
objs = [obj1, obj2, obj3]
names = ['obj1', 'obj2', 'obj3']

# Create map from geometry IDs to objects
geom_id_to_obj = { id(geom) : obj for geom, obj in zip(geoms, objs) }

# Create map from geometry IDs to string names
geom_id_to_name = { id(geom) : name for geom, name in zip(geoms, names) }

# Create manager
manager = fcl.DynamicAABBTreeCollisionManager()
manager.registerObjects(objs)
manager.setup()

# Create collision request structure
crequest = fcl.CollisionRequest(num_max_contacts=100, enable_contact=True)
cdata = fcl.CollisionData(crequest, fcl.CollisionResult())

# Run collision request
manager.collide(cdata, fcl.defaultCollisionCallback)

# Extract collision data from contacts and use that to infer set of
# objects that are in collision
objs_in_collision = set()

for contact in cdata.result.contacts:
    # Extract collision geometries that are in contact
    coll_geom_0 = contact.o1
    coll_geom_1 = contact.o2

    # Get their names
    coll_names = [geom_id_to_name[id(coll_geom_0)], geom_id_to_name[id(coll_geom_1)]]
    coll_names = tuple(sorted(coll_names))
    objs_in_collision.add(coll_names)

for coll_pair in objs_in_collision:
    print('Object {} in collision with object {}!'.format(coll_pair[0], coll_pair[1]))
```

```
>>> Object obj1 in collision with object obj2!
```
Let me know if you have any further questions.

**Comment by lt5bf** [comment]
This is fantastic and exactly what I'm looking for, thank you!

**Comment by mmatl** [comment]
No problem, great question! I added this information to the readme.

Also, if you're interested in doing collision checking on more complex shapes (i.e. triangular meshes, for example), I'd recommend looking at [trimesh](https://github.com/mikedh/trimesh). I wrote a wrapper for python-fcl in there (see `trimesh.collision.py` for the collision manager there) that does exactly this.

Best,
Matt

**Comment by chaiban** [comment]
HI, I am working on collision detection between many objects in the scene. Assuming I have 2 mesh objects with pose of each object in the world. How can I append them into scene for collision check ?. I looked at trimesh.scene but I am getting confused with all the parameters. Do you have a simple example for appending 2 meshes into scene ? 
Please share it if possible -- thank you.
