### ISSUE TITLE
Non compatible with NumPy 2.0.0

### ISSUE THREAD

**Issue by IvolgaDmitriy** [BerkeleyAutomation/python-fcl#80]
## Problem description
When creating a new virtual environment, `pip install trimesh[all]` was fully installed to use the collision module. Code using `trimesh.collision.The CollisionManager` did not start. When working in detail with the environment, an error occurred when installing `python-fcl`:
```
File "src/fcl/fcl.pyx", line 1, in init fcl.fcl
ValueError: numpy.dtype size changed, may indicate binary incompatibility. Expected 96 from C header, got 88 from PyObject
```
The problem disappears only when you pre-install numpy with version 1.*

## Steps to reproduce the problem:
1. `pip install python-fcl`
1. `import fcl`  

or  
1. `pip install numpy`
1. `pip install python-fcl`
1. `import fcl`

## Mediocre solution
1. `pip install numpy==1.*`
2. `pip install python-fcl`

Thank you in advance

**Comment by warenick** [comment]
I faced with the same issue.

**Comment by mikedh** [comment]
Hey, looks like there's a token permission issue preventing it from being released to PyPi but I triggered a rebuild which used Numpy 2 and the wheels from the release appear to work: https://github.com/BerkeleyAutomation/python-fcl/releases/tag/v0.7.0.7

**Comment by IvolgaDmitriy** [comment]
Thank you very much! The wheels are working. We are waiting for the release on pipy.
